
/**     @module/class likeness.TransformError
    @super Error

@String #code
    A String Error code intended to remain stable and reliable. If you need to branch on the type of
    Error that occured, this is your String. Possible values are:
     * `INVALID` A [ValidationError](likeness.ValidationError) was generated by the input \
        document or post-transform validation of the target.
     * `FORMAT` Failed to parse a String for `.cast` or `.group`.
     * `ILLEGAL` Unexpected extra keys, keys rejected by `.key`.
     * `LIMIT` Transform violates length constraints.
     * `SYNC` An asynchronous `.transform` constraint could not be processed.
@String #path
    The period-delimited deep path where the Error occurred.
@member input
    The input value which caused the Error, if defined.
@ValidationError|undefined #validationError
*/

var util = require ('util');

function TransformError (code, input, path, message, verr) {
    this.code = code;
    this.input = input;
    this.path = path;
    this.message = message;
    if (verr) this.validationError = verr;

    Error.call (this);
}
util.inherits (TransformError, Error);

module.exports = TransformError;
